server:
  port: 8100
  servlet:
    session:
      timeout: 20m
  error:
    path: error.html
spring:
  datasource:
    #主数据连接datasource下面没有别的层级 直接配置 多数据源时 增加一个层级如bdcinfo 然后下面在接配置
    type: com.alibaba.druid.pool.DruidDataSource
    jdbc-url: jdbc:mysql://127.0.0.1:3306/creditcard?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: pmc
    password: 123456
      #在mysql8之前 请用com.mysql.jdbc.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
#连接池参数，初始数、最大数、最小数、获取连接等待超时时间（毫秒）
    initial-size: 5
    max-active: 20
    min-idle: 5
    max-wait: 60000
##1
#spring.datasource.bdcinfo.driver-class-name=oracle.jdbc.driver.OracleDriver
#spring.datasource.bdcinfo.jdbc-url=jdbc:oracle:thin:@//192.168.0.182:1521/orcl
#spring.datasource.bdcinfo.username=BDCINFO
#spring.datasource.bdcinfo.password=1
##2
#spring.datasource.netobdc.driver-class-name=oracle.jdbc.driver.OracleDriver
#spring.datasource.netobdc.jdbc-url=jdbc:oracle:thin:@//192.168.0.182:1521/orcl
#spring.datasource.netobdc.username=netobdc
#spring.datasource.netobdc.password=1
#bdcinfo
    bdcinfo:
      type: com.alibaba.druid.pool.DruidDataSource
      jdbc-url: jdbc:mysql://127.0.0.1:3306/creditcard?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      username: pmc
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
#      jdbc-url: jdbc:oracle:thin:@//192.168.0.182:1521/orcl
#      username: bdcinfo
#      password: 1
#      driver-class-name: oracle.jdbc.driver.OracleDriver
      #连接池参数，初始数、最大数、最小数、获取连接等待超时时间（毫秒）
      initial-size: 5
      max-active: 20
      min-idle: 5
      max-wait: 60000
    #netobdc
    netobdc:
      type: com.alibaba.druid.pool.DruidDataSource
      jdbc-url: jdbc:mysql://127.0.0.1:3306/creditcard?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      username: pmc
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
      #连接池参数，初始数、最大数、最小数、获取连接等待超时时间（毫秒）
      initial-size: 5
      max-active: 20
      min-idle: 5
      max-wait: 60000
  #redies
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # 连接超时时间（毫秒）
    timeout: 10000
    # Redis服务器连接密码（默认为空）
    password:
    # 连接池最大连接数（使用负值表示没有限制） 默认 8
    lettuce:
      pool:
        max-active: 8
        # 连接池中的最大空闲连接 默认 8
        max-idle: 8
        # 连接池中的最小空闲连接 默认 0
        min-idle: 0
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: 10000
        # 关闭超时时间
        shutdown-timeout: 1000
#mybites
mybatis:
  #对应实体类路径
  typeAliasesPackage: com.example.demo.model
  mapperLocations: classpath*:mapper/*.xml
  #控制台打印sql
  configuration:
    log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl
#pagehelper设置分页数据库类型
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  #返回分页信息
  returnPageInfo: check